### ISSUE TITLE
Basic features

### ISSUE THREAD

**Issue by h1p3rcub3** [gwenaelp/vue-diagrams#1]
I found your awesome library and i love how easy to use it is but i'm missing some basic features to make it production ready. Is this proyect abandoned?

- Is it possible to edit the Diagram.Model properties? I would like to edit the width or the gridSnap, but setting a width with "diagram.Mode.width = X" does nothing. Maybe adding some config to the constructor?
- Is there any event that is called when a node is selected or clicked? I know i can check them individually, but it doesn't seem very eficient. 
- Adding a "label" inside the node would be great. 
- How do you delete links? Every time i press one it creates a new dot. 

Maybe this features are already there, but i couldn't find any documentation appart from the example and i'm not good at understanding code.

**Comment by gwenaelp** [comment]
It has clearly not been abandonned, but at the moment, due to lack of activity on this project and due to huge work load on other projects, I have not pushed it so far.

I will do it, as I will need a fully functional library sooner or later, but I can't dedicate too much time on it if I am not sure people will use it.

Thus, glad to see you here ! I will try to spend some time working on it ASAP then.

All those points are actually not yet implemented, and are relevant. I will create an issue for every remark for people to be able to track changes on them.

**Comment by kosirm** [comment]
+1
Count on me as frequent user. I can also report bugs etc.
